# Generated by Django 4.0.1 on 2022-01-25 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('character_class', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('hit_points', models.IntegerField()),
                ('spell_attack_bonus', models.IntegerField()),
                ('spell_save_dc', models.IntegerField()),
                ('strength_saving_throw', models.IntegerField()),
                ('dexterity_saving_throw', models.IntegerField()),
                ('constitution_saving_throw', models.IntegerField()),
                ('intelligence_saving_throw', models.IntegerField()),
                ('wisdom_saving_throw', models.IntegerField()),
                ('charisma_saving_throw', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('to_hit_bonus', models.CharField(max_length=50)),
                ('damage_bonus', models.CharField(max_length=50)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.character')),
            ],
        ),
    ]
