# Generated by Django 4.0.1 on 2022-01-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapons',
            name='damage_dice',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weapons',
            name='damage_bonus',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weapons',
            name='to_hit_bonus',
            field=models.IntegerField(),
        ),
    ]
